Fix missing include of math.h
Needed for round(). Otherwise build fails with GCC 6.x:
```
dirbrowser/randplayer.cpp: In member function ‘void RandPlayer::selectNextGroup()’:
dirbrowser/randplayer.cpp:86:39: error: ‘round’ was not declared in this scope
     int istart = vgstarts[round(fstart)];
```